---
- hosts: all
  tasks:
    - name: copy dotfiles
      copy: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }} backup=yes
      with_items:
        - ackrc
        - bin/
        - curlrc
        - editorconfig
        - gemrc
        - gitconfig
        - gitignore-global
        - hushlogin
        - tmux.conf
        - vimrc
        - zpreztorc
        - zshrc
        - zsh.prompts/
        - git.local
        - zshrc.local

    - name: create some directories
      file: path=~/.{{ item }} state=directory
      with_items:
        - bin.local
        - vim

    - name: clone zprezto
      git:
        repo: 'https://github.com/sorin-ionescu/prezto.git'
        dest: '~/.zprezto'
        recursive: yes

    - name: clone vim plugin manager
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '~/.vim/bundle/Vundle.vim'

    - name: install vim plugins
      command: vim -i NONE -c PluginInstall -c PluginClean! -c quitall

    - name: clone tmux plugin manager
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: '~/.tmux/plugins/tpm'
