---
- hosts: all
  tasks:
    - name: make links to dotfiles
      file: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - ackrc
        - curlrc
        - editorconfig
        - gemrc
        - gitconfig
        - gitignore-global
        - hushlogin
        - tmux.conf
        - vimrc
        - zpreztorc
        - zshrc
        - zsh.prompts

    - name: copy local dotfiles templates
      copy: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }} force=no
      with_items:
        - git.local
        - zshrc.local

    - name: clone zprezto
      git:
        repo: 'https://github.com/sorin-ionescu/prezto.git'
        dest: '~/.zprezto'
        recursive: yes

    - name: create a .vim directory
      file: path=~/.vim state=directory

    - name: clone vim plugin manager
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '~/.vim/bundle/Vundle.vim'

    - name: install vim plugins
      command: vim -i NONE -c PluginInstall -c PluginClean! -c quitall
