---
- hosts: all
  vars:
    dotfiles_dir: '~/.dotfiles'
  tasks:
    - name: clone dotfiles repo to local ~/.dotfiles
      git:
        repo: 'https://github.com/nksoff/dotfiles.git'
        accept_hostkey: yes
        dest: '{{ dotfiles_dir }}'

    - name: detect dotfiles to be linked
      shell: ls {{ dotfiles_dir }}/files | grep -v '.local'
      register: dotfiles_link

    - name: detect dotfiles to be copied
      shell: ls {{ dotfiles_dir }}/files | grep '.local'
      register: dotfiles_copy

    - name: link dotfiles to be linked
      file: src={{ dotfiles_dir }}/files/{{ item }} dest=~/.{{ item }} state=link force=yes
      with_items: '{{ dotfiles_link.stdout_lines }}'

    - name: copy dotfiles to be copied
      copy: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }} force=no
      with_items: '{{ dotfiles_copy.stdout_lines }}'

    - name: clone antigen
      git:
        repo: 'https://github.com/zsh-users/antigen.git'
        dest: '~/.antigen'
        recursive: yes

    - name: clone vim plugin manager
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '~/.vim/bundle/Vundle.vim'

    - name: install vim plugins
      command: vim -i NONE -c PluginInstall -c PluginClean! -c quitall

    - name: clone tmux plugin manager
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: '~/.tmux/plugins/tpm'
